### PR TITLE
Fixes #26323 - Remove max_tasks_per_child setting

### PR DESCRIPTION
**Pull request by chris1984**
Will open up Refs prs to the other modules that have this setting including katello-devel so they can be merged after this one is accepted.

### CODE REVIEW

**Comment by ehelms** [comment]
Was this setting removed from Pulp or have they deprecated it's use? If not, I think we need to keep this here and only remove it form modules that use this module.

**Comment by chris1984** [comment]
Proxy pr:
https://github.com/theforeman/puppet-foreman_proxy_content/pull/196

**Comment by chris1984** [comment]
@ehelms the feature is still there just not being moved over with Pulp 3. I am fine with that suggestion on just removing it from our stuff.

**Comment by ekohl** [comment]
I agree with @ehelms that as long as it's a feature, it's fine to keep it in. We don't need to expose it as a top level parameter though.

**Comment by chris1984** [comment]
Closing based on discussions, will just keep the katello/proxy-content one open and make a migration for the installer.

**Pull request closed without merging**
